import CategoriesSidebar from "./../../components/CategoriesSidebar";
export const metadata = {
  title: "Categories",
  description: "Generated by create next app",
};
export default function Categories({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row gap-4 p-4">
      <div className="w-1/4 bg-gray-800 p-4 rounded-lg shadow-lg overflow-y-auto h-screen">
        <CategoriesSidebar />
      </div>
      <div className="w-3/4">{children}</div>
    </div>
  );
}
