import "./globals.css";
import { Josefin_Sans } from "next/font/google";
import Header from "./../components/Header";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Trendify",
  description: "Generated by create next app",
};

const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} bg-gray-900 container mx-auto text-white`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
